/// <summary>
/// Enumeration of possible EventIDs, defining types of events that can be triggered in the system.
/// </summary>
public enum EventID{
    None = 0,
    ResetWalkableTile,
    AddMoreObstacle,
    ObstacleTileSpawned,
    InitializeUpdatePhaseChanging,
    ChangePhase,
    ObstacleCube_Collide,
    Player_Collide,
    Player_TakeCoin,
    ButtonPauseGame_Click,
    ButtonResumeGameRunning_Click,
    ButtonResumeGameRestarting_Click,
    ChangeGameState,
    EnterMainMenuState,
    EnterGameRunningState,
    EnterGamePausedState,
    EnterGameOverState,
    EnterGameRestartingState,
    EnterGameResultState,
    EnterStartTrasitionState,
    EnterEndTrasitionState,
    ADS_WatchFullAds,
    GameOver_FinishGameOver,
    FinishRestarting,
    ButtonPlayGame_Click,
    ButtonReloadGame_Click,
    LoadCoinsData,
    LoadCurrentSpaceShipData,
    LoadSpaceShipOwnedData,
    SetCurrentSpaceShipSuccess,
    SpaceShipItem_SelectedItem,
    SpaceShipItem_OwnedItemClick,
    WantToBuyItem,
    SpaceShipItem_BuySuccess,
    CoinItem_BuySuccess,
    Item_BuyFailed,
    ButtonShopping_Click,
    ButtonHome_Click,
    FinishCalculateTotalCoin,
    BaseButton_Click,
    ButtonMusic_Click,
    WantToWatch_ADS,
}