/// <summary>
/// Defines types of parameters that can be sent within a triggered event.
/// Enum constants follow the format 'EventID_KeyName' for clarity.
/// </summary>
public enum EventParameterType{
    None = 0,
    ResetWalkableTile_WalkableTileObject,
    AddMoreObstacle_ListObstaclePrefab,
    ObstacleTileSpawned_WalkableTileObjectAndListSpawnPositions,
    InitializeUpdatePhaseChanging_Null,
    ChangePhase_Null,
    ObstacleCube_Collide_ObjCollision,
    Player_Collide_PlayerObject,
    Player_TakeCoin_Null,
    ButtonPauseGame_Click_Null,
    ButtonResumeGameRunning_Click_Null,
    ButtonResumeGameRestarting_Click_Null,
    ChangeGameState_GameState,
    EnterMainMenuState_Null,
    EnterGameRunningState_Null,
    EnterGamePausedState_Null,
    EnterGameOverState_Null,
    EnterGameRestartingState_Null,
    EnterGameResultState_Null,
    EnterEndTrasitionState_Null,
    EnterStartTrasitionState_Null,
    ADS_WatchFullAds_Placement,
    GameOver_FinishGameOver_Null,
    FinishRestarting_Null,
    ButtonPlayGame_Click_Null,
    ButtonReloadGame_Click_Null,
    LoadCoinsData_NumCoinAdded,
    LoadCurrentSpaceShipData_CurrentSpaceShipID,
    LoadSpaceShipOwnedData_SpaceShipOwnedIDs,
    SetCurrentSpaceShipSuccess_Null,
    SpaceShipItem_SelectedItem_SpaceShipConfig,
    SpaceShipItem_OwnedItemClick_SpaceShipConfig,
    WantToBuyItem_Item,
    SpaceShipItem_BuySuccess_SpaceShipConfigID,
    CoinItem_BuySuccess_CoinConfigID,
    Item_BuyFailed_Null,
    ButtonShopping_Click_Null,
    ButtonHome_Click_Null,
    FinishCalculateTotalCoin_Null,
    BaseButton_Click_Null,
    ButtonMusic_Click_Null,
    WantToWatch_ADS_PlacementID,
}